version: "2.4"

services:
  cloud-config-server:
    image: acipi/cipitech:cloud-config-server-1.1.0-SNAPSHOT
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: bind
        source: /data/bootstrap
        target: /data/bootstrap
        read_only: true
    ports:
      - "8888:8888"
      - "8887:8887"
    networks:
      - net
    restart: always
    mem_limit: 512m
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "cipitech"

networks:
  net:
    driver: bridge