version: '3.3'

services:
  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=elasticsearch1
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data1:/usr/share/elasticsearch/data
      - logs1:/usr/share/elasticsearch/logs
      - config1:/usr/share/elasticsearch/config
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    networks:
      - esnet
      
  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/usr/share/elasticsearch/data
      - logs2:/usr/share/elasticsearch/logs
      - config2:/usr/share/elasticsearch/config
    networks:
      - esnet

volumes: # Define seperate volume for Elasticsearch data
  data1:
    driver: local
  config1:
    driver: local
  logs1:
    driver: local
  data2:
    driver: local
  config2:
    driver: local
  logs2:
    driver: local
    
networks:
  esnet: