version: '2.4'

services:
  rabbitmq:
    build:
      context: ./
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    #Rabbitmq uses the hostname as part of the folder name in the mnesia directory. 
    #Mnesia is the directory where the rabbitMQ data are stored.
    hostname: "cipitech-rabbit"
    environment:
      #Default username and password are guest/guest
      - "RABBITMQ_DEFAULT_USER=rabbitmq"
      - "RABBITMQ_DEFAULT_PASS=rabbitmq"
      - "RABBITMQ_VM_MEMORY_HIGH_WATERMARK=512MiB"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - net
    restart: always
    mem_limit: 512m
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "rabbitmq"
      
volumes:
  rabbitmq_data:
    driver: local
    
networks:
  net:
    driver: bridge