server.name: kibana
server.host: "0"

## X-Pack security credentials
# Send Monitoring Data
xpack.monitoring.enabled: true
xpack.monitoring.kibana.collection.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true
#Monitoring cluster
xpack.monitoring.elasticsearch.hosts: ["http://10.0.2.15:9200"]
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: mypassword
#xpack.monitoring.elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt


#Production cluster
elasticsearch.hosts: [ "http://10.0.2.15:9200" ]
elasticsearch.username: elastic
elasticsearch.password: mypassword
#elasticsearch.ssl.verificationMode: none
#elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt