version: '3.5'

services:
  mysql-db:
    build:
      context: ./
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    environment:
      - "MYSQL_ROOT_PASSWORD=zk4Vy8sv"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - net
    restart: always
    mem_limit: 2g
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "mysql"
      
volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
    
networks:
  net:
    driver: bridge