version: '3.7'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zk4Vy8sv
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - "3306:3306"
    networks:
      - net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2g"
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "mysql"
  
  mysql_db_backup:
    image: databack/mysql-backup:latest
    environment:
      #DB_DUMP_CRON: "30 3 * * *"
      DB_DUMP_FREQ: 1440
      DB_DUMP_BEGIN: +10
      DB_DUMP_TARGET: /backup
      DB_DUMP_BY_SCHEMA: "true"
      DB_NAMES: "wordpress sys"
      DB_USER: root
      DB_PASS: zk4Vy8sv
      DB_SERVER: mysql_db
      DB_DUMP_DEBUG: "true"
      #MYSQLDUMP_OPTS: "--single-transaction"
    volumes:
      - mysql_backup:/backup
    networks:
      - net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1g"
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "mysql-backup"
      
volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  mysql_backup:
    driver: local
    
networks:
  net:
    driver: bridge
