version: "2.4"

services:
  eureka-server:
    image: acipi/cipitech:eureka-server-$APP_VERSION
    environment:
      - "JAVA_OPTS=-Xms$MEM_LIMIT -Xmx$MEM_LIMIT"
      - spring.profiles.active=$APP_STAGE,docker
      - spring.cloud.bootstrap.location=/data/bootstrap/cipitech-eureka-server/,/data/bootstrap/
    volumes:
      - type: bind
        source: /data/bootstrap
        target: /data/bootstrap
        read_only: true
    ports:
      - "8761:8761"
      - "8762:8762"
    networks:
      - net
    restart: always
    mem_limit: $MEM_LIMIT
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "cipitech"

networks:
  net:
    driver: bridge