version: '2.4'

services:
  mongo-db:
    build:
      context: ./db/
      args:
        MONGO_VERSION: $MONGO_VERSION
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - net
    restart: always
    mem_limit: 512m
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "mongo"

  mongo-dashboard:
    build:
      context: ./dashboard/
      args:
        MONGO_EXPRESS_VERSION: $MONGO_EXPRESS_VERSION
    environment:
      # When they are on the same network
      - "ME_CONFIG_MONGODB_SERVER=mongo-db"
      - "ME_CONFIG_MONGODB_PORT=27017"
      # The credentials to login to the admin interface
      - "ME_CONFIG_BASICAUTH_USERNAME=mongo"
      - "ME_CONFIG_BASICAUTH_PASSWORD=mongo"
      # The credentials of the mongo server
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=example"
    ports:
      - "8091:8081"
    networks:
      - net
    restart: always
    mem_limit: 512m
    logging:
      options:
        max-size: 200m
        max-file: "10"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      log_group: "mongo-express"
      
volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
    
networks:
  net:
    driver: bridge